version: '3'

services:

  api:
    build:
      context: .
    tty: true
    ports:
      - 8000:8000
    command: >
      sh -c 'uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000 --reload'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://root:pass123@mongo:27017/
    ports:
      - 8081:8081

